Stop instance + clean up on server shutdown
Cypheruim/minebot pull request #7
Opened 2021-09-12 18:36 UTC by OnePunMan

Previously, the launch flow had two issues:
1. The instance does not stop when the server is stopped
2. Stopping the server does not properly clean up background processes, they will linger until manually killed or detect that the server is stopped and stops themselves

This PR resolves the aforementioned issues:
1. Whenever the MC server stops, it will shut down the system (shutting STOPs the instance, not TERMINATE)
2. Whenever the MC server stops, it will (gracefully) stop its child cron process

Makefile changes:
1. `make run` will now shut down the instance after its run. Avoid using this command locally as it will shut down your own computer
2. `make local` won't initiate shutdown after the server stops. Use this if you want to test things locally
3. The startup and shutdown logic has been moved to `launch.sh` and `shutdown.sh` respectively

2021-09-12 23:27 UTC, Cypheruim commented on shutdown.sh
>  # This script shutsdown the instanace
This script shuts down the instance

(spelling)

2021-09-13 17:05 UTC, george-lim requested changes

2021-09-13 17:05 UTC, george-lim commented on Makefile
> +	./launch.sh
you don't need this line since install already calls `./launch.sh`

2021-09-13 17:05 UTC, george-lim commented on core/cron.py
> +    logger.warning(f"Received stop signal: {sig_num} ({signal.Signals(sig_num).name})")
Question: is this really a warning though? You're expecting this to get called, so it's not like there's anything to be cautious about. I would probably have used `logger.info` since you're not catching unexpected exceptions.

2021-09-13 17:05 UTC, george-lim commented on core/cron.py
> +        num_checks = 0
Unused variable

2021-09-13 17:05 UTC, george-lim commented on launch.sh
> +trap kill_child_processes SIGINT SIGTERM
I recognize this code 😂

2021-09-13 17:05 UTC, george-lim commented on shutdown.sh
> +shutsdown now
I'm pretty sure this is supposed to be `shutdown now` lol
Did you have a chance to test this?

2021-09-13 17:23 UTC, Cypheruim commented on core/cron.py
>          logger.warning(f"stop_server() failed, probably because the server is already stopped. There shouldn't be any fatal side effects. Error: {traceback.format_exc()}")
f string not supported with the default python version ec2 comes with. Either we use .format or we have to upgrade python during startup. 

Opinion on which one we should do?

2021-09-13 17:24 UTC, george-lim commented on Makefile
> +	./launch.sh
nevermind I'm dumb, I assumed `local: install` was `install`

2021-09-13 18:42 UTC, george-lim commented on core/cron.py
>          logger.warning(f"stop_server() failed, probably because the server is already stopped. There shouldn't be any fatal side effects. Error: {traceback.format_exc()}")
@Cypheruim good catch. It's generally not a good idea to update system packages (because they could break other system programs, or have unintended side effects), and since this change is quite trivial I would just switch to `.format`.

That being said, we should keep an eye out for other parts of our code that depend on Python features unavailable in EC2's system python. If we find that our scripts break without the latest version of python, it might be worth the investment to install the latest Python 3 in `/usr/lib` and explicitly reference that path for Python when executing our scripts.

2021-09-13 18:44 UTC, george-lim commented on core/cron.py
>          logger.info(f"Checker is now running...")
Note: Having a linter would probably catch this.

2021-09-13 18:49 UTC, george-lim commented on core/cron.py
>          logger.warning(f"stop_server() failed, probably because the server is already stopped. There shouldn't be any fatal side effects. Error: {traceback.format_exc()}")
FYI @Cypheruim just a tip - it would be nice if you included a link to the official amazon docs or something that shows what version EC2 does come with, so that Jackie can find other parts of the code that might have the same issue.

Note: using a python version manager like [pyenv](https://github.com/pyenv/pyenv) with this project would probably solve this issue in the future. The idea is that you specify the version of python that this project requires, and if you use the version manager it will automatically switch to using the version you specify when you are testing / running code locally from within the project folder. You can catch these compatibility issues during testing.

2021-09-14 01:26 UTC, OnePunMan commented on core/cron.py
> +        num_checks = 0
It's used later in the while loop

2021-09-14 01:27 UTC, OnePunMan commented on shutdown.sh
> +shutsdown now
Good catch

2021-09-14 14:55 UTC, OnePunMan commented on core/cron.py
>          logger.warning(f"stop_server() failed, probably because the server is already stopped. There shouldn't be any fatal side effects. Error: {traceback.format_exc()}")
I just confirmed that our current EC2 has Python 3.7, which means f-strings are supported, thankfully. We just have to ensure that all commands are run via `python3` instead of just `python`

2021-09-14 15:06 UTC, Cypheruim commented on core/cron.py
>          logger.warning(f"stop_server() failed, probably because the server is already stopped. There shouldn't be any fatal side effects. Error: {traceback.format_exc()}")
sounds good just ensure that we are using 'python3' then.

I do think we should freeze the python version as well so things don't break in the future but this will do for now

2021-09-14 15:08 UTC, Cypheruim approved these changes
Looks good I'll merge it now

2021-09-14 15:08 UTC, merged